export MODE_RUN=0
export SHORT_DEFAULT_MODE='E'
export TYPE_NOHUP_OUT='default_table_23_VAZC'
export ORDER_NOHUP='TSR_TT23_VAZC_DEFAULT_92'
export ORDER_TRAIN_EVAL='TT23_VAZC_DEFAULT_92'

# export MODE_RUN=0
# export SHORT_DEFAULT_MODE='E'
# export TYPE_NOHUP_OUT='default_table_BHXH'
# export ORDER_NOHUP='TSR_TT_BHXH_DEFAULT_1'
# export ORDER_TRAIN_EVAL='TT_BHXH_DEFAULT_1'

# export MODE_RUN=2
# export SHORT_DEFAULT_MODE='T'
# export TYPE_NOHUP_OUT='grid_search_table_23_VAZC'
# export ORDER_NOHUP='TSR_TT23_VAZC_GRID_SEARCH_13'
# export ORDER_TRAIN_EVAL='TT23_VAZC_GRID_SEARCH_13'

export TRAIN_TYPE='TSR'
export TABLE_TYPE='23_VAZC'
export SETUP_FILE_DIR='../setup/setup.txt'

echo $MODE_RUN > $SETUP_FILE_DIR
echo $SHORT_DEFAULT_MODE >> $SETUP_FILE_DIR
echo $TYPE_NOHUP_OUT >> $SETUP_FILE_DIR
echo $ORDER_NOHUP >> $SETUP_FILE_DIR
echo $ORDER_TRAIN_EVAL >> $SETUP_FILE_DIR
echo $TRAIN_TYPE >> $SETUP_FILE_DIR
echo $TABLE_TYPE >> $SETUP_FILE_DIR